### ISSUE TITLE
ERR_INCOMPLETE_CHUNKED_ENCODING

### ISSUE THREAD

**Issue by Per0x** [fanout/pushpin#47664] opened 2019-02-22 16:54 UTC
This error appears in chrome when my app is behind pushpin (in Docker, last ver 1.19.1-1). ERR_INCOMPLETE_CHUNKED_ENCODING
It takes a refresh several times to make it disappear, and the site is slower.

**Comment by kevinswiber** [comment] 2019-02-22 22:27
It sounds like the response is coming back with the header `Transfer-Encoding: chunked` but is not terminating correctly.  Chrome likely has a timeout set for chunked responses.  There's a chance Chrome is not receiving the terminating sequence (`0\r\n\r\n`) from Pushpin before that timeout is reached.

Do you have a minimal test case we can use to reproduce the issue?

**Comment by Per0x** [comment] 2019-02-22 22:36
Sorry, I can't provide a minimal case to reproduce the issue as my app is for internal use. 
The error sometimes appears as from the login page, and in Firefox it's almost the same thing, with sometimes missing graphic elements.

**Comment by kevinswiber** [comment] 2019-02-23 00:31
@Per0x Sure.  Do you see any errors in the Pushpin logs?

**Comment by Per0x** [comment] 2019-02-23 01:10
I put you the logs of the only types of error/warn I have in my logs:

[INFO] [proxy] GET http://IP:7999/xxx -> IP:80 ref=http://IP:7999/xxx error
[INFO] [proxy] POST http://IP:7999/xxx ref=http://IP:7999/xxx error
[WARN] [handler] IN pull: received message with invalid format (tnetstring parse failed), skipping
[WARN] [handler] zrpc server: received message with parts != 1, skipping

There doesn't seem to be a log generated when it specifically appears, so I don't know if if these ones are relevant or not.
But I noticed that Chrome displays the error 50% of the time, and sometimes it displays the error but just after, the page loads correctly (without F5).

**Comment by jkarneges** [comment] 2019-02-23 04:01
The "zrpc server" warning is the kind of thing that should never happen, so that's suspicious. Are you using the official Pushpin docker package or did you build your own?

The "IN pull" warning is also unusual. Are you publishing data to Pushpin's ZeroMQ PULL interface? If not, then I wonder if there is some interference.

**Comment by Per0x** [comment] 2019-02-23 11:30
Yes I'm using the official docker image from Docker Hub, I didn't build it myself.
I deleted the container and started a brand new one. Errors still appears, but in the logs the only one present are of the type:
```
[INFO] [proxy] GET http://IP:7999/xxx -> IP:80 ref=http://IP:7999/xxx error
[INFO] [proxy] POST http://IP:7999/xxx ref=http://IP:7999/xxx error
```
No zrpc server and IN pull warning this time.
I'm not publishing to ZeroMQ PULL interface, what kind of interference could it be ?

**Comment by Per0x** [comment] 2019-02-27 01:41
I give news. I updated the container with Pushpin 1.20 and I used another port instead of the default 7999, and  the error seems to have disappeared.

**Comment by jkarneges** [comment] 2019-02-27 17:49
Thanks for the update. The only way I can think of the "IN pull" warning appearing when you're not using the PULL interface would be if libzmq or Qt were behaving screwy. Maybe some ABI incompatibility between package versions that resolved itself when we rebuilt.

I'll close this issue now, but if you ever see anything like this again please re-open.

**Closed by jkarneges** 2019-02-27 17:49 UTC

**Comment by dandamian83** [comment] 2019-07-05 09:23
Hi, I'm having the same problem.
I'm developing a react app, and I'm using pushpin for stateless websockets. 
I have pushpin running on my mac (192.168.1.100:3000) and the react app on my dev laptop (192.168.1.140:3000).
In routes I have 192.168.1.140:3000,over_http

Form time to time, when I change my react files, and react reloads automatically it's client, I get in Chrome's Developer Console: 
```
GET http://192.168.1.100:3000/static/js/0.chunk.js net::ERR_INCOMPLETE_CHUNKED_ENCODING 200 (OK)
DevTools failed to parse SourceMap: http://192.168.1.100:3000/static/js/1.chunk.js.map
```
If I click on "DevTools failed to parse SourceMap: http://192.168.1.100:3000/static/js/1.chunk.js.map" the source of 1.chunk.js.map is shown and I can see an empty or incomplete file.

I then click refresh several times without success. 
Only by accessing the app from a totally new Chrome Window solves the problem.
After successfully accessing the app in the new window, it starts working (after a refresh) also in the old one.

In my pushpin-proxy.log I see the following: 
```
[INFO] 2019-07-05 12:12:12.491 GET http://192.168.1.100:3000/login -> 192.168.1.140:3000 code=304 0

[INFO] 2019-07-05 12:12:12.533 GET http://192.168.1.100:3000/static/js/bundle.js -> 192.168.1.140:3000 ref=http://192.168.1.100:3000/login code=304 0

[INFO] 2019-07-05 12:12:12.562 GET http://192.168.1.100:3000/static/js/main.chunk.js -> 192.168.1.140:3000 ref=http://192.168.1.100:3000/login code=304 0

[INFO] 2019-07-05 12:12:12.564 GET http://192.168.1.100:3000/main.9d94baa813bec31d82a0.hot-update.js -> 192.168.1.140:3000 ref=http://192.168.1.100:3000/login code=304 0

[INFO] 2019-07-05 12:12:12.582 GET http://192.168.1.100:3000/static/js/0.chunk.js -> 192.168.1.140:3000 ref=http://192.168.1.100:3000/login code=200 223824

[INFO] 2019-07-05 12:12:13.003 GET http://192.168.1.100:3000/static/js/main.chunk.js.map -> 192.168.1.140:3000 code=304 0

[INFO] 2019-07-05 12:12:13.011 GET http://192.168.1.100:3000/static/js/bundle.js.map -> 192.168.1.140:3000 code=304 0

[INFO] 2019-07-05 12:12:13.050 GET http://192.168.1.100:3000/main.9d94baa813bec31d82a0.hot-update.js.map -> 192.168.1.140:3000 code=304 0

[INFO] 2019-07-05 12:12:13.090 GET http://192.168.1.100:3000/favicon.ico -> 192.168.1.140:3000 ref=http://192.168.1.100:3000/login code=200 3870
```

So a lot of 304 Not Modified status.

**Comment by jkarneges** [comment] 2019-07-08 17:17
Hi, what Pushpin, Zurl, and Mongrel2 versions?

**Comment by dandamian83** [comment] 2019-07-08 17:43
I have pushpin 1.23.0. I've just installed pushpin these days. I don't know how can I find the versions of each exe from pushpin, but what I can tell you is that I've installed pushpin on macOs using brew, so a pre-compiled version.

**Comment by jannic** [comment] 2019-07-10 20:43
Hi @dandamian83, I tried to reproduce the issue, without success. The next thing I could try would be using the 'create-react-app' script you mentioned. Did you you anything specific, or is it enough to follow the quick-start guide at https://github.com/facebook/create-react-app and access the generated app through pushpin?
Does the error occur every time after the react app was reloaded, or does it take multiple attempts?

**Comment by dandamian83** [comment] 2019-07-11 13:18
Exactly. Create a react app, using the script. Then start changing some files in the app. The 'file change monitor' script/process will auto-refresh the app in the browser. Then you will see the error.

**Comment by jannic** [comment] 2019-07-11 16:56
I still can't reproduce the issue.
Tried it with:
- npm/npx 5.8.0
- react 16.8.6
- chromium 73.0.3683.75 from debian sid
Everything running on debian, I don't have a macOS system.

**Comment by dandamian83** [comment] 2019-07-11 20:19
I'm running React on my PC so on Windows, and the pushpin instance on my Mac. Both my pc and mac are running in the same local network. 
I'm using react 16.8.6, npm/npx 6.4.1 and Google Chrome Version 75.0.3770.100 (Official Build) (64-bit).

**Comment by jannic** [comment] 2019-07-11 21:13
Upgrading to the same version of Google Chrome (but on Linux) didn't change anything, either.

**Comment by dandamian83** [comment] 2019-07-12 06:53
Have you tried to repeatedly change the source code of the app so that the app should be auto-reloaded? The error appears after some reloads (2-3, maybe even 5)...
Also, please note that my pusphin instance resides on a different machine than my app.

**Comment by habib786** [comment] 2021-12-02 09:24
Is there any update on this error? 
I'm still facing this issue and after refreshing multiple time, it was fixed by why did it gives this error on the first load? 
Is there any fix available rather than updating node version etc?
